

# Thème
theme: minima

# Build settings
destination: docs
markdown: kramdown

# Collections
collections:
  chapitres:
    output: true
    permalink: /:path/

# Exclusions
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Minima settings
minima:
  skin: classic
  social_links:
    github: SurnumerismeAuthor