site_name: "SURNUMERISME : Une Théorie économique travailliste"
docs_dir: docs
theme:
  name: material
  palette:
    - scheme: default
      primary: teal  # Couleur verte principale (teal est une teinte verte douce)
      accent: green  # Accent vert pour les interactions
    - scheme: slate
      primary: teal
      accent: green
  features:
    - navigation.instant
    - navigation.sections
    - content.tabs
nav:

  - Accueil: index.md
  - Sommaire: sommaire.md
  - Introduction: introduction.md
  - Chapitre 1: chapitre1.md
  - Chapitre 2: chapitre2.md
  - Chapitre 3: chapitre3.md
  - Chapitre 4: chapitre4.md
  - Chapitre 5: chapitre5.md
  - Chapitre 6: chapitre6.md
  - Chapitre 7: chapitre7.md
  - Chapitre 8: chapitre8.md
  - Chapitre 9: chapitre9.md
  - Chapitre 10: chapitre10.md
  - Chapitre 11: chapitre11.md
plugins:
  - search
  - mermaid2
markdown_extensions:
  - pymdownx.superfences
extra_css:
  - overrides/css/custom.css