site_name: "Surnumérisme : Une Théorie Médiane pour une Économie Humaine et Globale"
theme:
  name: material
nav:
  - Accueil: index.md
  - Sommaire: sommaire.md
  - Introduction: introduction.md  # Minuscule pour matcher le fichier
  - Chapitre 1: chapitre1.md
  - Chapitre 2: chapitre2.md
  - Chapitre 3: chapitre3.md
  - Chapitre 4: chapitre4.md
  - Chapitre 5: chapitre5.md
  - Chapitre 6: chapitre6.md
  - Chapitre 7: chapitre7.md
  - Chapitre 8: chapitre8.md
  - Chapitre 9: chapitre9.md
  - Chapitre 10: chapitre10.md
  - Chapitre 11: chapitre11.md
plugins:
  - search