name: Deploy Surnumérisme Site

on:
  schedule:
    - cron: '0 18 19 10 *'  # 18h UTC = 19h WAT, 19 oct
  workflow_dispatch:  # Lancement manuel

jobs:
  deploy:
    runs-on: ubuntu-latest  # Environnement cloud, pas ton PC
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Version spécifique
      - run: pip install --upgrade pip
      - run: pip install mkdocs mkdocs-material ghp-import
      - run: mkdocs build
      - run: ghp-import -n -p -m "Déploiement baptême 19 oct 2025" site